#include "../include/opcodes.h"

const x86_afrm_tables_t X86_AFRM_TABLES[] = {
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EAX]"}, 0x00, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[ECX]"}, 0x01, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EDX]"}, 0x02, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EBX]"}, 0x03, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { NULL  }, 0x04, 0x1},
    {"AL", "AX", "EAX", "MM0", "XMM0", { NULL }, 0x05,  0x1},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[ESI]"}, 0x06, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[EDI]"}, 0x07, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EAX]"}, 0x08, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[ECX]"}, 0x09, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EDX]"}, 0x0A, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EBX]"}, 0x0B, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", {   NULL }, 0x0C, 0x1},
    {"CL", "CX", "ECX", "MM1", "XMM1", {   NULL }, 0x0D, 0x1},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[ESI]" }, 0x0E, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EDI]"}, 0x0F,  0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EAX]"}, 0x10,  0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[ECX]"}, 0x11,  0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EDX]"}, 0x12,  0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EBX]" }, 0x13, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { NULL    }, 0x14, 0x1},
    {"DL", "DX", "EDX", "MM2", "XMM2", { NULL    }, 0x15, 0x1},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[ESI]" }, 0x16, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EDI]" }, 0x17, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EAX]"}, 0x18, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[ECX]"}, 0x19, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EDX]"}, 0x1A, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EBX]"}, 0x1B, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { NULL   }, 0x1C, 0x1},
    {"BL", "BX", "EBX", "MM3", "XMM3", { NULL   }, 0x1D, 0x1},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[ESI]"}, 0x1E, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EDI]"}, 0x1F, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EAX]"}, 0x20, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[ECX]"}, 0x21, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EDX]"}, 0x22, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EBX]"}, 0x23, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", {  NULL  }, 0x24, 0x1},
    {"AH", "SP", "ESP", "MM4", "XMM4", {  NULL  }, 0x25, 0x1},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[ESI]"}, 0x26, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EDI]"}, 0x27, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EAX]"}, 0x28, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[ECX]"}, 0x29, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EDX]"}, 0x2A, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EBX]"}, 0x2B, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { NULL   }, 0x2C, 0x1},
    {"CH", "BP", "EBP", "MM5", "XMM5", { NULL   }, 0x2D, 0x1},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[ESI]"}, 0x2E, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EDI]"}, 0x2F, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EAX]"}, 0x30, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[ECX]"}, 0x31, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EDX]"}, 0x32, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EBX]"}, 0x33, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { NULL   }, 0x34, 0x1},
    {"DH", "SI", "ESI", "MM6", "XMM6", { NULL   }, 0x35, 0x1},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[ESI]"}, 0x36, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EDI]"}, 0x37, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EAX]"}, 0x38, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[ECX]"}, 0x39, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EDX]"}, 0x3A, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EBX]"}, 0x3B, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { NULL   }, 0x3C, 0x1},
    {"BH", "DI", "EDI", "MM7", "XMM7", { NULL   }, 0x3D, 0x1},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[ESI]"}, 0x3E, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EDI]"}, 0x3F, 0x0},

    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EAX +"}, 0x40, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[ECX +"}, 0x41, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EDX +"}, 0x42, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EBX +"}, 0x43, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { NULL  }, 0x44, 0x1},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[EBP +" }, 0x45,  0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[ESI +"}, 0x46, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[EDI +"}, 0x47, 0x0},

    {"CL", "CX", "ECX", "MM1", "XMM1", {"[EAX +"}, 0x48, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", {"[ECX +"}, 0x49, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", {"[EDX +"}, 0x4A, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", {"[EBX +"}, 0x4B, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { NULL  }, 0x4C, 0x1},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EBP +" }, 0x4D,  0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[ESI +"}, 0x4E, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EDI +"}, 0x4F, 0x0},

    {"DL", "DX", "EDX", "MM2", "XMM2", {"[EAX +"}, 0x50, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", {"[ECX +"}, 0x51, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", {"[EDX +"}, 0x52, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", {"[EBX +"}, 0x53, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { NULL  }, 0x54, 0x1},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EBP +" }, 0x55,  0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[ESI +"}, 0x56, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EDI +"}, 0x57, 0x0},

    {"BL", "BX", "EBX", "MM3", "XMM3", {"[EAX +"}, 0x58, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", {"[ECX +"}, 0x59, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", {"[EDX +"}, 0x5A, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", {"[EBX +"}, 0x5B, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { NULL  }, 0x5C, 0x1},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EBP +" }, 0x5D,  0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[ESI +"}, 0x5E, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EDI +"}, 0x5F, 0x0},

    {"AH", "SP", "ESP", "MM4", "XMM4", {"[EAX +"}, 0x60, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", {"[ECX +"}, 0x61, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", {"[EDX +"}, 0x62, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", {"[EBX +"}, 0x63, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { NULL  }, 0x64, 0x1},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EBP +" }, 0x65,  0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[ESI +"}, 0x66, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EDI +"}, 0x67, 0x0},

    {"CH", "BP", "EBP", "MM5", "XMM5", {"[EAX +"}, 0x68, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", {"[ECX +"}, 0x69, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", {"[EDX +"}, 0x6A, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", {"[EBX +"}, 0x6B, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { NULL  }, 0x6C, 0x1},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EBP +" }, 0x6D,  0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[ESI +"}, 0x6E, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EDI +"}, 0x6F, 0x0},

    {"DH", "SI", "ESI", "MM6", "XMM6", {"[EAX +"}, 0x70, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", {"[ECX +"}, 0x71, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", {"[EDX +"}, 0x72, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", {"[EBX +"}, 0x73, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { NULL  }, 0x74, 0x1},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EBP +" }, 0x75,  0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[ESI +"}, 0x76, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EDI +"}, 0x77, 0x0},

    {"BH", "DI", "EDI", "MM7", "XMM7", {"[EAX +"}, 0x78, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", {"[ECX +"}, 0x79, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", {"[EDX +"}, 0x7A, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", {"[EBX +"}, 0x7B, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { NULL  }, 0x7C, 0x1},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EBP +" }, 0x7D,  0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[ESI +"}, 0x7E, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EDI +"}, 0x7F, 0x0},


    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EAX +"}, 0x80, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[ECX +"}, 0x81, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EDX +"}, 0x82, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", {"[EBX +"}, 0x83, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { NULL  }, 0x84, 0x1},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[EBP +" }, 0x85,  0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[ESI +"}, 0x86, 0x0},
    {"AL", "AX", "EAX", "MM0", "XMM0", { "[EDI +"}, 0x87, 0x0},

    {"CL", "CX", "ECX", "MM1", "XMM1", {"[EAX +"}, 0x88, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", {"[ECX +"}, 0x89, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", {"[EDX +"}, 0x8A, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", {"[EBX +"}, 0x8B, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { NULL  }, 0x8C, 0x1},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EBP +" }, 0x8D,  0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[ESI +"}, 0x8E, 0x0},
    {"CL", "CX", "ECX", "MM1", "XMM1", { "[EDI +"}, 0x8F, 0x0},

    {"DL", "DX", "EDX", "MM2", "XMM2", {"[EAX +"}, 0x90, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", {"[ECX +"}, 0x91, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", {"[EDX +"}, 0x92, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", {"[EBX +"}, 0x93, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { NULL  }, 0x94, 0x1},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EBP +" }, 0x95,  0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[ESI +"}, 0x96, 0x0},
    {"DL", "DX", "EDX", "MM2", "XMM2", { "[EDI +"}, 0x97, 0x0},

    {"BL", "BX", "EBX", "MM3", "XMM3", {"[EAX +"}, 0x98, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", {"[ECX +"}, 0x99, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", {"[EDX +"}, 0x9A, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", {"[EBX +"}, 0x9B, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { NULL  }, 0x9C, 0x1},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EBP +" }, 0x9D,  0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[ESI +"}, 0x9E, 0x0},
    {"BL", "BX", "EBX", "MM3", "XMM3", { "[EDI +"}, 0x9F, 0x0},

    {"AH", "SP", "ESP", "MM4", "XMM4", {"[EAX +"}, 0xA0, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", {"[ECX +"}, 0xA1, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", {"[EDX +"}, 0xA2, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", {"[EBX +"}, 0xA3, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { NULL  }, 0xA4, 0x1},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EBP +" }, 0xA5,  0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[ESI +"}, 0xA6, 0x0},
    {"AH", "SP", "ESP", "MM4", "XMM4", { "[EDI +"}, 0xA7, 0x0},

    {"CH", "BP", "EBP", "MM5", "XMM5", {"[EAX +"}, 0xA8, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", {"[ECX +"}, 0xA9, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", {"[EDX +"}, 0xAA, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", {"[EBX +"}, 0xAB, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { NULL  }, 0xAC, 0x1},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EBP +" }, 0xAD,  0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[ESI +"}, 0xAE, 0x0},
    {"CH", "BP", "EBP", "MM5", "XMM5", { "[EDI +"}, 0xAF, 0x0},

    {"DH", "SI", "ESI", "MM6", "XMM6", {"[EAX +"}, 0xB0, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", {"[ECX +"}, 0xB1, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", {"[EDX +"}, 0xB2, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", {"[EBX +"}, 0xB3, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { NULL  }, 0xB4, 0x1},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EBP +" }, 0xB5,  0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[ESI +"}, 0xB6, 0x0},
    {"DH", "SI", "ESI", "MM6", "XMM6", { "[EDI +"}, 0xB7, 0x0},

    {"BH", "DI", "EDI", "MM7", "XMM7", {"[EAX +"}, 0xB8, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", {"[ECX +"}, 0xB9, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", {"[EDX +"}, 0xBA, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", {"[EBX +"}, 0xBB, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { NULL  }, 0xBC, 0x1},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EBP +" }, 0xBD,  0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[ESI +"}, 0xBE, 0x0},
    {"BH", "DI", "EDI", "MM7", "XMM7", { "[EDI +"}, 0xBF, 0x0},

    { "AL", "AX", "EAX", "MM0", "XMM0", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xC0, 0x0},
    { "AL", "AX", "EAX", "MM0", "XMM0", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xC1, 0x0},
    { "AL", "AX", "EAX", "MM0", "XMM0", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xC2, 0x0},
    { "AL", "AX", "EAX", "MM0", "XMM0", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xC3, 0x0},
    { "AL", "AX", "EAX", "MM0", "XMM0", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xC4, 0x0},
    { "AL", "AX", "EAX", "MM0", "XMM0", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xC5, 0x0},
    { "AL", "AX", "EAX", "MM0", "XMM0", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xC6, 0x0},
    { "AL", "AX", "EAX", "MM0", "XMM0", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xC7, 0x0},

    { "CL", "CX", "ECX", "MM1", "XMM1", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xC8, 0x0},
    { "CL", "CX", "ECX", "MM1", "XMM1", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xC9, 0x0},
    { "CL", "CX", "ECX", "MM1", "XMM1", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xCA, 0x0},
    { "CL", "CX", "ECX", "MM1", "XMM1", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xCB, 0x0},
    { "CL", "CX", "ECX", "MM1", "XMM1", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xCC, 0x0},
    { "CL", "CX", "ECX", "MM1", "XMM1", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xCD, 0x0},
    { "CL", "CX", "ECX", "MM1", "XMM1", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xCE, 0x0},
    { "CL", "CX", "ECX", "MM1", "XMM1", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xCF, 0x0},

    { "DL", "DX", "EDX", "MM2", "XMM2", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xD0, 0x0},
    { "DL", "DX", "EDX", "MM2", "XMM2", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xD1, 0x0},
    { "DL", "DX", "EDX", "MM2", "XMM2", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xD2, 0x0},
    { "DL", "DX", "EDX", "MM2", "XMM2", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xD3, 0x0},
    { "DL", "DX", "EDX", "MM2", "XMM2", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xD4, 0x0},
    { "DL", "DX", "EDX", "MM2", "XMM2", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xD5, 0x0},
    { "DL", "DX", "EDX", "MM2", "XMM2", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xD6, 0x0},
    { "DL", "DX", "EDX", "MM2", "XMM2", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xD7, 0x0},

    { "BL", "BX", "EBX", "MM3", "XMM3", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xD8, 0x0},
    { "BL", "BX", "EBX", "MM3", "XMM3", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xD9, 0x0},
    { "BL", "BX", "EBX", "MM3", "XMM3", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xDA, 0x0},
    { "BL", "BX", "EBX", "MM3", "XMM3", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xDB, 0x0},
    { "BL", "BX", "EBX", "MM3", "XMM3", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xDC, 0x0},
    { "BL", "BX", "EBX", "MM3", "XMM3", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xDD, 0x0},
    { "BL", "BX", "EBX", "MM3", "XMM3", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xDE, 0x0},
    { "BL", "BX", "EBX", "MM3", "XMM3", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xDF, 0x0},

    { "AH", "SP", "ESP", "MM4", "XMM4", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xE0, 0x0},
    { "AH", "SP", "ESP", "MM4", "XMM4", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xE1, 0x0},
    { "AH", "SP", "ESP", "MM4", "XMM4", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xE2, 0x0},
    { "AH", "SP", "ESP", "MM4", "XMM4", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xE3, 0x0},
    { "AH", "SP", "ESP", "MM4", "XMM4", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xE4, 0x0},
    { "AH", "SP", "ESP", "MM4", "XMM4", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xE5, 0x0},
    { "AH", "SP", "ESP", "MM4", "XMM4", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xE6, 0x0},
    { "AH", "SP", "ESP", "MM4", "XMM4", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xE7, 0x0},


    { "CH", "BP", "EBP", "MM5", "XMM5", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xE8, 0x0},
    { "CH", "BP", "EBP", "MM5", "XMM5", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xE9, 0x0},
    { "CH", "BP", "EBP", "MM5", "XMM5", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xEA, 0x0},
    { "CH", "BP", "EBP", "MM5", "XMM5", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xEB, 0x0},
    { "CH", "BP", "EBP", "MM5", "XMM5", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xEC, 0x0},
    { "CH", "BP", "EBP", "MM5", "XMM5", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xED, 0x0},
    { "CH", "BP", "EBP", "MM5", "XMM5", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xEE, 0x0},
    { "CH", "BP", "EBP", "MM5", "XMM5", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xEF, 0x0},

    { "DH", "SI", "ESI", "MM6", "XMM6", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xF0, 0x0},
    { "DH", "SI", "ESI", "MM6", "XMM6", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xF1, 0x0},
    { "DH", "SI", "ESI", "MM6", "XMM6", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xF2, 0x0},
    { "DH", "SI", "ESI", "MM6", "XMM6", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xF3, 0x0},
    { "DH", "SI", "ESI", "MM6", "XMM6", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xF4, 0x0},
    { "DH", "SI", "ESI", "MM6", "XMM6", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xF5, 0x0},
    { "DH", "SI", "ESI", "MM6", "XMM6", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xF6, 0x0},
    { "DH", "SI", "ESI", "MM6", "XMM6", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xF7, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "EAX", "AX", "AL", "MM0", "XMM0"}, 0xF8, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "ECX", "CX", "CL", "MM1", "XMM1"}, 0xF9, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "EDX", "DX", "DL", "MM2", "XMM2"}, 0xFA, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "EBX", "BX", "BL", "MM3", "XMM3"}, 0xFB, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "ESP", "SP", "AH", "MM4", "XMM4"}, 0xFC, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "EBP", "BP", "CH", "MM5", "XMM5"}, 0xFD, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "ESI", "SI", "DH", "MM6", "XMM6"}, 0xFE, 0x0},
    { "BH", "DI", "EDI", "MM7", "XMM7", { "EDI", "DI", "BH", "MM7", "XMM7"}, 0xFF, 0x0},


};