#include "opcodes.h"

/* The [*] nomenclature means a disp32 with no base if the MOD is 00B. Otherwise, [*] means disp8 or disp32 + [EBP]. This provides the
following address modes:
MOD bits Effective Address
00 [scaled index] + disp32 
01 [scaled index] + disp8 + [EBP]
10 [scaled index] + disp32 + [EBP]
*/

const x86_afsib_tables_t X86_AFSIB_TABLES[] = {
    {"EAX", "[EAX]", 0x00},
    {"ECX", "[EAX]", 0x01},
    {"EDX", "[EAX]", 0x02},
    {"EBX", "[EAX]", 0x03},
    {"ESP", "[EAX]", 0x04},
    {"[*]", "[EAX]", 0x05},
    {"ESI", "[EAX]", 0x06},
    {"EDI", "[EAX]", 0x07},
    {"EAX", "[ECX]", 0x08},
    {"ECX", "[ECX]", 0x09},
    {"EDX", "[ECX]", 0x0A},
    {"EBX", "[ECX]", 0x0B},
    {"ESP", "[ECX]", 0x0C},
    {"[*]", "[ECX]", 0x0D},
    {"ESI", "[ECX]", 0x0E},
    {"EDI", "[ECX]", 0x0F},
    {"EAX", "[EDX]", 0x10},
    {"ECX", "[EDX]", 0x11},
    {"EDX", "[EDX]", 0x12},
    {"EBX", "[EDX]", 0x13},
    {"ESP", "[EDX]", 0x14},
    {"[*]", "[EDX]", 0x15},
    {"ESI", "[EDX]", 0x16},
    {"EDI", "[EDX]", 0x17},
    {"EAX", "[EBX]", 0x18},
    {"ECX", "[EBX]", 0x19},
    {"EDX", "[EBX]", 0x1A},
    {"EBX", "[EBX]", 0x1B},
    {"ESP", "[EBX]", 0x1C},
    {"[*]", "[EBX]", 0x1D},
    {"ESI", "[EBX]", 0x1E},
    {"EDI", "[EBX]", 0x1F},
    {"EAX", NULL, 0x20},
    {"ECX", NULL, 0x21},
    {"EDX", NULL, 0x22},
    {"EBX", NULL, 0x23},
    {"ESP", NULL, 0x24},
    {"[*]", NULL, 0x25},
    {"ESI", NULL, 0x26},
    {"EDI", NULL, 0x27},
    {"EAX", "[EBP]", 0x28},
    {"ECX", "[EBP]", 0x29},
    {"EDX", "[EBP]", 0x2A},
    {"EBX", "[EBP]", 0x2B},
    {"ESP", "[EBP]", 0x2C},
    {"[*]", "[EBP]", 0x2D},
    {"ESI", "[EBP]", 0x2E},
    {"EDI", "[EBP]", 0x2F},
    {"EAX", "[ESI]", 0x30},
    {"ECX", "[ESI]", 0x31},
    {"EDX", "[ESI]", 0x32},
    {"EBX", "[ESI]", 0x33},
    {"ESP", "[ESI]", 0x34},
    {"[*]", "[ESI]", 0x35},
    {"ESI", "[ESI]", 0x36},
    {"EDI", "[ESI]", 0x37},
    {"EAX", "[EDI]", 0x38},
    {"ECX", "[EDI]", 0x39},
    {"EDX", "[EDI]", 0x3A},
    {"EBX", "[EDI]", 0x3B},
    {"ESP", "[EDI]", 0x3C},
    {"[*]", "[EDI]", 0x3D},
    {"ESI", "[EDI]", 0x3E},
    {"EDI", "[EDI]", 0x3F},

    {"EAX", "[EAX * 2]", 0x40},
    {"ECX", "[EAX * 2]", 0x41},
    {"EDX", "[EAX * 2]", 0x42},
    {"EBX", "[EAX * 2]", 0x43},
    {"ESP", "[EAX * 2]", 0x44},
    {"[*]", "[EAX * 2]", 0x45},
    {"ESI", "[EAX * 2]", 0x46},
    {"EDI", "[EAX * 2]", 0x47},

    {"EAX", "[ECX * 2]", 0x48},
    {"ECX", "[ECX * 2]", 0x49},
    {"EDX", "[ECX * 2]", 0x4A},
    {"EBX", "[ECX * 2]", 0x4B},
    {"ESP", "[ECX * 2]", 0x4C},
    {"[*]", "[ECX * 2]", 0x4D},
    {"ESI", "[ECX * 2]", 0x4E},
    {"EDI", "[ECX * 2]", 0x4F},

    {"EAX", "[EDX * 2]", 0x50},
    {"ECX", "[EDX * 2]", 0x51},
    {"EDX", "[EDX * 2]", 0x52},
    {"EBX", "[EDX * 2]", 0x53},
    {"ESP", "[EDX * 2]", 0x54},
    {"[*]", "[EDX * 2]", 0x55},
    {"ESI", "[EDX * 2]", 0x56},
    {"EDI", "[EDX * 2]", 0x57},

    {"EAX", "[EBX * 2]", 0x58},
    {"ECX", "[EBX * 2]", 0x59},
    {"EDX", "[EBX * 2]", 0x5A},
    {"EBX", "[EBX * 2]", 0x5B},
    {"ESP", "[EBX * 2]", 0x5C},
    {"[*]", "[EBX * 2]", 0x5D},
    {"ESI", "[EBX * 2]", 0x5E},
    {"EDI", "[EBX * 2]", 0x5F},

    {"EAX", NULL, 0x60},
    {"ECX", NULL, 0x61},
    {"EDX", NULL, 0x62},
    {"EBX", NULL, 0x63},
    {"ESP", NULL, 0x64},
    {"[*]", NULL, 0x65},
    {"ESI", NULL, 0x66},
    {"EDI", NULL, 0x67},

    {"EAX", "[EBP * 2]", 0x68},
    {"ECX", "[EBP * 2]", 0x69},
    {"EDX", "[EBP * 2]", 0x6A},
    {"EBX", "[EBP * 2]", 0x6B},
    {"ESP", "[EBP * 2]", 0x6C},
    {"[*]", "[EBP * 2]", 0x6D},
    {"ESI", "[EBP * 2]", 0x6E},
    {"EDI", "[EBP * 2]", 0x6F},

    {"EAX", "[ESI * 2]", 0x70},
    {"ECX", "[ESI * 2]", 0x71},
    {"EDX", "[ESI * 2]", 0x72},
    {"EBX", "[ESI * 2]", 0x73},
    {"ESP", "[ESI * 2]", 0x74},
    {"[*]", "[ESI * 2]", 0x75},
    {"ESI", "[ESI * 2]", 0x76},
    {"EDI", "[ESI * 2]", 0x77},

    {"EAX", "[EDI * 2]", 0x78},
    {"ECX", "[EDI * 2]", 0x79},
    {"EDX", "[EDI * 2]", 0x7A},
    {"EBX", "[EDI * 2]", 0x7B},
    {"ESP", "[EDI * 2]", 0x7C},
    {"[*]", "[EDI * 2]", 0x7D},
    {"ESI", "[EDI * 2]", 0x7E},
    {"EDI", "[EDI * 2]", 0x7F},

    {"EAX", "[EAX * 4]", 0x80},
    {"ECX", "[EAX * 4]", 0x81},
    {"EDX", "[EAX * 4]", 0x82},
    {"EBX", "[EAX * 4]", 0x83},
    {"ESP", "[EAX * 4]", 0x84},
    {"[*]", "[EAX * 4]", 0x85},
    {"ESI", "[EAX * 4]", 0x86},
    {"EDI", "[EAX * 4]", 0x87},

    {"EAX", "[ECX * 4]", 0x88},
    {"ECX", "[ECX * 4]", 0x89},
    {"EDX", "[ECX * 4]", 0x8A},
    {"EBX", "[ECX * 4]", 0x8B},
    {"ESP", "[ECX * 4]", 0x8C},
    {"[*]", "[ECX * 4]", 0x8D},
    {"ESI", "[ECX * 4]", 0x8E},
    {"EDI", "[ECX * 4]", 0x8F},

    {"EAX", "[EDX * 4]", 0x90},
    {"ECX", "[EDX * 4]", 0x91},
    {"EDX", "[EDX * 4]", 0x92},
    {"EBX", "[EDX * 4]", 0x93},
    {"ESP", "[EDX * 4]", 0x94},
    {"[*]", "[EDX * 4]", 0x95},
    {"ESI", "[EDX * 4]", 0x96},
    {"EDI", "[EDX * 4]", 0x97},

    {"EAX", "[EBX * 4]", 0x98},
    {"ECX", "[EBX * 4]", 0x99},
    {"EDX", "[EBX * 4]", 0x9A},
    {"EBX", "[EBX * 4]", 0x9B},
    {"ESP", "[EBX * 4]", 0x9C},
    {"[*]", "[EBX * 4]", 0x9D},
    {"ESI", "[EBX * 4]", 0x9E},
    {"EDI", "[EBX * 4]", 0x9F},

    {"EAX", NULL, 0xA0},
    {"ECX", NULL, 0xA1},
    {"EDX", NULL, 0xA2},
    {"EBX", NULL, 0xA3},
    {"ESP", NULL, 0xA4},
    {"[*]", NULL, 0xA5},
    {"ESI", NULL, 0xA6},
    {"EDI", NULL, 0xA7},

    {"EAX", "[EBP * 4]", 0xA8},
    {"ECX", "[EBP * 4]", 0xA9},
    {"EDX", "[EBP * 4]", 0xAA},
    {"EBX", "[EBP * 4]", 0xAB},
    {"ESP", "[EBP * 4]", 0xAC},
    {"[*]", "[EBP * 4]", 0xAD},
    {"ESI", "[EBP * 4]", 0xAE},
    {"EDI", "[EBP * 4]", 0xAF},

    {"EAX", "[ESI * 4]", 0xB0},
    {"ECX", "[ESI * 4]", 0xB1},
    {"EDX", "[ESI * 4]", 0xB2},
    {"EBX", "[ESI * 4]", 0xB3},
    {"ESP", "[ESI * 4]", 0xB4},
    {"[*]", "[ESI * 4]", 0xB5},
    {"ESI", "[ESI * 4]", 0xB6},
    {"EDI", "[ESI * 4]", 0xB7},

    {"EAX", "[EDI * 4]", 0xB8},
    {"ECX", "[EDI * 4]", 0xB9},
    {"EDX", "[EDI * 4]", 0xBA},
    {"EBX", "[EDI * 4]", 0xBB},
    {"ESP", "[EDI * 4]", 0xBC},
    {"[*]", "[EDI * 4]", 0xBD},
    {"ESI", "[EDI * 4]", 0xBE},
    {"EDI", "[EDI * 4]", 0xBF},

    {"EAX", "[EAX * 8]", 0xC0},
    {"ECX", "[EAX * 8]", 0xC1},
    {"EDX", "[EAX * 8]", 0xC2},
    {"EBX", "[EAX * 8]", 0xC3},
    {"ESP", "[EAX * 8]", 0xC4},
    {"[*]", "[EAX * 8]", 0xC5},
    {"ESI", "[EAX * 8]", 0xC6},
    {"EDI", "[EAX * 8]", 0xC7},

    {"EAX", "[ECX * 8]", 0xC8},
    {"ECX", "[ECX * 8]", 0xC9},
    {"EDX", "[ECX * 8]", 0xCA},
    {"EBX", "[ECX * 8]", 0xCB},
    {"ESP", "[ECX * 8]", 0xCC},
    {"[*]", "[ECX * 8]", 0xCD},
    {"ESI", "[ECX * 8]", 0xCE},
    {"EDI", "[ECX * 8]", 0xCF},

    {"EAX", "[EDX * 8]", 0xD0},
    {"ECX", "[EDX * 8]", 0xD1},
    {"EDX", "[EDX * 8]", 0xD2},
    {"EBX", "[EDX * 8]", 0xD3},
    {"ESP", "[EDX * 8]", 0xD4},
    {"[*]", "[EDX * 8]", 0xD5},
    {"ESI", "[EDX * 8]", 0xD6},
    {"EDI", "[EDX * 8]", 0xD7},

    {"EAX", "[EBX * 8]", 0xD8},
    {"ECX", "[EBX * 8]", 0xD9},
    {"EDX", "[EBX * 8]", 0xDA},
    {"EBX", "[EBX * 8]", 0xDB},
    {"ESP", "[EBX * 8]", 0xDC},
    {"[*]", "[EBX * 8]", 0xDD},
    {"ESI", "[EBX * 8]", 0xDE},
    {"EDI", "[EBX * 8]", 0xDF},

    {"EAX", NULL, 0xE0},
    {"ECX", NULL, 0xE1},
    {"EDX", NULL, 0xE2},
    {"EBX", NULL, 0xE3},
    {"ESP", NULL, 0xE4},
    {"[*]", NULL, 0xE5},
    {"ESI", NULL, 0xE6},
    {"EDI", NULL, 0xE7},

    {"EAX", "[EBP * 8]", 0xE8},
    {"ECX", "[EBP * 8]", 0xE9},
    {"EDX", "[EBP * 8]", 0xEA},
    {"EBX", "[EBP * 8]", 0xEB},
    {"ESP", "[EBP * 8]", 0xEC},
    {"[*]", "[EBP * 8]", 0xED},
    {"ESI", "[EBP * 8]", 0xEE},
    {"EDI", "[EBP * 8]", 0xEF},

    {"EAX", "[ESI * 8]", 0xF0},
    {"ECX", "[ESI * 8]", 0xF1},
    {"EDX", "[ESI * 8]", 0xF2},
    {"EBX", "[ESI * 8]", 0xF3},
    {"ESP", "[ESI * 8]", 0xF4},
    {"[*]", "[ESI * 8]", 0xF5},
    {"ESI", "[ESI * 8]", 0xF6},
    {"EDI", "[ESI * 8]", 0xF7},

    {"EAX", "[EDI * 8]", 0xF8},
    {"ECX", "[EDI * 8]", 0xF9},
    {"EDX", "[EDI * 8]", 0xFA},
    {"EBX", "[EDI * 8]", 0xFB},
    {"ESP", "[EDI * 8]", 0xFC},
    {"[*]", "[EDI * 8]", 0xFD},
    {"ESI", "[EDI * 8]", 0xFE},
    {"EDI", "[EDI * 8]", 0xFF},
};